baseURL: http://qachadoimoveis.com/
languageCode: pt-br
title: QAchado outlet de imóveis
theme: "hugo-fresh"
googleAnalytics: G-0E0TCQYWTP
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description: QAchado é um site de busca de imóveis de leilão extrajudicial e imóveis com desconto, especializado nos imóveis Caixa. Encontrar imóvel barato é aqui mesmo!
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/ACHADO.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Encontre imóveis com descontos incríveis
    # Hero subtitle (optional)
    subtitle: O Qachado é o maior e mais completo serviço de busca de imóveis de leilão extrajudicial. Um banco de dados completo e atualizado diariamente. Imóveis Caixa - Leilões, venda direta, venda online, licitações e muito mais. Imóveis com até 90% de desconto. Economize tempo utilizando filtros de busca avançados. Experimente!
    # Button text
    buttontext: Acessar plataforma de imóveis
    # Where the main hero button links to
    buttonlink: "https://qachado.netlify.app"
    # Hero image (from static/images/___)
    image: illustrations/capa_ex.png
    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Quem somos
    url: /quem_somos/index.html
  - title: Assine já
    url: /assine
  - title: Blog
    url: /blog/como_mantemos_a_base_de_imoveis/index.html
  # - title: Dropdown
  #   sublinks:
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  # - title: Entrar
  #   url: /
  # - title: Sign up
  #   url: /
    # button: true
  # sidebar:
  #   # Logo (from /images/logos/___.svg)
  #   logo: fresh-square
  #   sections:
  #   - title: User
  #     icon: user
  #     links:
  #     - text: Profile
  #       url: /
  #     - text: Account
  #       url: /
  #     - text: Settings
  #       url: /
  #   - title: Messages
  #     icon: envelope
  #     links:
  #     - text: Inbox
  #       url: /
  #     - text: Compose
  #       url: /
  #   - title: Images
  #     icon: image
  #     links:
  #     - text: Library
  #       url: /
  #     - text: Upload
  #       url: /
  #   - title: Settings
  #     icon: cog
  #     links:
  #     - text: User settings
  #       url: /
  #     - text: App settings
  #       url: /
  section1:
    title: Grandes oportunidades ao seu alcance
    subtitle: de maneira fácil e rápida
    tiles:
    - title: Atualizado diariamente
      icon: atualizado
      text: Vasculhamos o site da Caixa todos os dias. Fique atento e saia na frente.
      url: /blog/como_mantemos_a_base_de_imoveis/index.html
      buttonText: Entenda
    - title: Filtros avançados
      icon: filtro
      text: Busque imóveis por estado, cidade, condições de pagamento muito mais.
      url: https://qachado.netlify.app
      buttonText: Experimentar
    - title: Economize tempo
      icon: favoritos
      text: Acesse rapidamente e gerencia sua lista de imóveis de interesse.
      url: https://qachado.netlify.app
      buttonText: Experimentar
    - title: Localize o imóvel
      icon: mapa
      text: Com um clique você estará no google maps, visitando o bairro e a rua do imóvel.
      url: https://qachado.netlify.app
      buttonText: Experimentar
  section2:
    title: Que tal comprar seu imóvel com descontos que podem chegar a até 90%?
    subtitle: Nós vamos te ajudar...
    features:
    - title: 1. Encontre seu imóvel
      text: Use nossa plataforma de busca e encontre o imóvel que atenda a seus requisitos.
      # Icon (from /images/illustrations/icons/___.svg)
      #icon: laptop-globe
    - title: 2. Saiba como comprar
      text: Nós te ensinamos o passo a passo para realizar uma compra com segurança. Explore nosso blog.
      #icon: doc-sync
    - title: 3. Conte com especialistas no assunto
      text: Caso não se sinta seguro, nós indicamos um corretor especialista, credenciado pela Caixa, que poderá te ajudar.
      #icon: mobile-feed
  section3:
    title: Plataforma
    subtitle: QAchado
    image: illustrations/mockups/app-view.png
    buttonText: Cadastre-se grátis
    buttonLink: "https://qachado.netlify.app"
  # section4:
  #   title: Our Clients love us!
  #   subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #   clients:
  #   - name: Irma Walters
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Accountant
  #     img: 1
  #   - name: John Bradley
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Financial Analyst
  #     img: 2
  #   - name: Gary Blackman
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: HR Manager
  #     img: 3
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: ACHADO_branco.png
    # Social Media Title
    socialmediatitle: Siga-nos
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://www.instagram.com/qachado.imoveis/
      icon: instagram
    # - link: https://facebook.com/#
    #   icon: facebook
    # - link: https://youtube.com/#
    #   icon: youtube
    bulmalogo: false
    # quicklinks:
    #   column1:
    #     title: "Product"
    #     links:
    #     - text: Discover features
    #       link: /
    #     - text: Why choose our product?
    #       link: /
    #     - text: Compare features
    #       link: /
    #     - text: Our roadmap
    #       link: /
    #     - text: AGB
    #       link: /agb
    #   column2:
    #     title: "Docs"
    #     links:
    #     - text: Get started
    #       link: /
    #     - text: User guides
    #       link: /
    #     - text: Admin guide
    #       link: /
    #     - text: Developers
    #       link: /
    #   column3:
    #     title: "Blog"
    #     links:
    #     - text: Latest news
    #       link: /blog/first
    #     - text: Tech articles
    #       link: /blog/second
