[build]
command = 'hugo'
publish = 'public'
[build.environment]
HUGO_VERSION = '0.101.0'

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'

[[redirects]]
  from = "/blog/rentabilidade"
  to = "/blog/rentabilidade_dos_imoveis_de_leilao"


[[redirects]]
  from = "/blog/venda_online"
  to = "/blog/vantagens_da_venda_online_caixa"


